# run: conda env create --file environment.yml

name: jupyter-binder
channels:
  - conda-forge
dependencies:
- python>=3.9
- jupyter
- jupyterlab
- nbgitpuller
- dask
- matplotlib
- earthaccess
- cartopy
- pydap
- pip
- pip:
  # Get these from pip until conda gets netCDF4 4.9.3++. jhrg 7/14/23
  - netCDF4
  - xarray
